"""Update fields

Revision ID: a55fa05cc170
Revises:
Create Date: 2026-05-21 20:24:12.825219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a55fa05cc170"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_armement_cooperatives_code", table_name="armement_cooperatives")
    op.drop_index("ix_armement_cooperatives_id", table_name="armement_cooperatives")
    op.drop_table("armement_cooperatives")
    # op.drop_table('topology')
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('layer')
    op.add_column(
        "debarcaderes", sa.Column("est_localise", sa.Boolean(), nullable=True)
    )
    op.create_foreign_key(
        None, "debarquements", "pecheurs", ["pecheur_principal_id"], ["id"]
    )
    op.drop_index("idx_permissions_code", table_name="permissions")
    op.drop_index("idx_permissions_module", table_name="permissions")
    op.drop_index("idx_role_permissions_permission", table_name="role_permissions")
    op.drop_index("idx_role_permissions_role", table_name="role_permissions")
    op.drop_index("idx_roles_code", table_name="roles")
    op.drop_index("idx_user_permissions_permission", table_name="user_permissions")
    op.drop_index("idx_user_permissions_user", table_name="user_permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_user_permissions_user", "user_permissions", ["user_id"], unique=False
    )
    op.create_index(
        "idx_user_permissions_permission",
        "user_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index("idx_roles_code", "roles", ["code"], unique=False)
    op.create_index(
        "idx_role_permissions_role", "role_permissions", ["role_id"], unique=False
    )
    op.create_index(
        "idx_role_permissions_permission",
        "role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index("idx_permissions_module", "permissions", ["module"], unique=False)
    op.create_index("idx_permissions_code", "permissions", ["code"], unique=False)
    op.drop_constraint(None, "debarquements", type_="foreignkey")
    op.drop_column("debarcaderes", "est_localise")
    op.create_table(
        "layer",
        sa.Column("topology_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("layer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("schema_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("table_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feature_column", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feature_type", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "level",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("child_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["topology_id"], ["topology.id"], name="layer_topology_id_fkey"
        ),
        sa.PrimaryKeyConstraint("topology_id", "layer_id", name="layer_pkey"),
        sa.UniqueConstraint(
            "schema_name",
            "table_name",
            "feature_column",
            name="layer_schema_name_table_name_feature_column_key",
        ),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    op.create_table(
        "topology",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hasz",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="topology_pkey"),
        sa.UniqueConstraint("name", name="topology_name_key"),
    )
    op.create_table(
        "armement_cooperatives",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "denomination", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("sigle", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("siege", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column(
            "type_association",
            postgresql.ENUM("ARMEMENT", "COOPERATIVE", name="typeassociation"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "adresse", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "telephone", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "site_web", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "province", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "departement", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "localite", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="armement_cooperatives_pkey"),
    )
    op.create_index(
        "ix_armement_cooperatives_id", "armement_cooperatives", ["id"], unique=False
    )
    op.create_index(
        "ix_armement_cooperatives_code", "armement_cooperatives", ["code"], unique=True
    )
    # ### end Alembic commands ###
