"""Add profile fields and activity_logs

Revision ID: 00f79ffd8ee0
Revises: 2547499bab75
Create Date: 2026-04-24 22:37:13.828674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00f79ffd8ee0"
down_revision: Union[str, None] = "2547499bab75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column("users", sa.Column("adresse", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("ville", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("code_postal", sa.String(length=10), nullable=True)
    )
    op.add_column("users", sa.Column("pays", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("photo_profil", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("signature", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("preferences", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "preferences")
    op.drop_column("users", "signature")
    op.drop_column("users", "photo_profil")
    op.drop_column("users", "pays")
    op.drop_column("users", "code_postal")
    op.drop_column("users", "ville")
    op.drop_column("users", "adresse")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
