"""Update user Role

Revision ID: 32533bfa14df
Revises: 3a3b517af929
Create Date: 2026-04-26 02:15:15.246951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32533bfa14df"
down_revision: Union[str, None] = "3a3b517af929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_index("idx_role_permissions_permission", table_name="role_permissions")
    op.drop_index("idx_role_permissions_role", table_name="role_permissions")
    op.drop_index("idx_user_permissions_permission", table_name="user_permissions")
    op.drop_index("idx_user_permissions_user", table_name="user_permissions")
    op.drop_index("idx_users_role", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_users_role", "users", ["role_id"], unique=False)
    op.create_index(
        "idx_user_permissions_user", "user_permissions", ["user_id"], unique=False
    )
    op.create_index(
        "idx_user_permissions_permission",
        "user_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        "idx_role_permissions_role", "role_permissions", ["role_id"], unique=False
    )
    op.create_index(
        "idx_role_permissions_permission",
        "role_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
