"""Update fields 2

Revision ID: 4df0787f1324
Revises: 69402e8570c4
Create Date: 2026-05-20 06:55:02.301599

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4df0787f1324"
down_revision: Union[str, None] = "69402e8570c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_armement_cooperatives_code", table_name="armement_cooperatives")
    op.drop_index("ix_armement_cooperatives_id", table_name="armement_cooperatives")
    op.drop_table("armement_cooperatives")
    op.alter_column(
        "debarcaderes",
        "milieu",
        existing_type=postgresql.ENUM(
            "MARITIME", "CONTINENTAL", "LAGUNAIRE", "HAUTURIERE", name="milieu"
        ),
        nullable=True,
    )
    op.alter_column(
        "debarcaderes",
        "geom",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        nullable=True,
    )
    op.alter_column(
        "debarcaderes",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "debarcaderes",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "debarcaderes",
        "longitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "debarcaderes",
        "latitude",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "debarcaderes",
        "geom",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        nullable=False,
    )
    op.alter_column(
        "debarcaderes",
        "milieu",
        existing_type=postgresql.ENUM(
            "MARITIME", "CONTINENTAL", "LAGUNAIRE", "HAUTURIERE", name="milieu"
        ),
        nullable=True,
    )
    op.create_table(
        "armement_cooperatives",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "denomination", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("sigle", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("siege", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column(
            "type_association",
            postgresql.ENUM("ARMEMENT", "COOPERATIVE", name="typeassociation"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "adresse", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "telephone", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "site_web", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "province", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "departement", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "localite", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="armement_cooperatives_pkey"),
    )
    op.create_index(
        "ix_armement_cooperatives_id", "armement_cooperatives", ["id"], unique=False
    )
    op.create_index(
        "ix_armement_cooperatives_code", "armement_cooperatives", ["code"], unique=True
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
