"""Update fields

Revision ID: 69402e8570c4
Revises: 4b87c9eb8a72
Create Date: 2026-05-20 06:51:07.933894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "69402e8570c4"
down_revision: Union[str, None] = "4b87c9eb8a72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_violations_licences_id", table_name="violations_licences")
    op.drop_table("violations_licences")
    op.drop_index("ix_inspections_licences_id", table_name="inspections_licences")
    op.drop_table("inspections_licences")
    op.drop_index(
        "ix_renouvellements_licences_id", table_name="renouvellements_licences"
    )
    op.drop_table("renouvellements_licences")
    op.drop_index("ix_armement_cooperatives_code", table_name="armement_cooperatives")
    op.drop_index("ix_armement_cooperatives_id", table_name="armement_cooperatives")
    op.drop_table("armement_cooperatives")
    op.drop_index("ix_licences_peche_id", table_name="licences_peche")
    op.drop_index("ix_licences_peche_numero_licence", table_name="licences_peche")
    op.drop_table("licences_peche")
    op.add_column(
        "debarcaderes",
        sa.Column(
            "milieu",
            sa.Enum(
                "MARITIME", "CONTINENTAL", "LAGUNAIRE", "HAUTURIERE", name="milieu"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("debarcaderes", "milieu")
    op.create_table(
        "licences_peche",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('licences_peche_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "numero_licence", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type_licence", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "categorie", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("pecheur_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("date_emission", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("date_debut", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("date_expiration", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "zone_peche", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("coordonnees_zone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "types_peche_autorises", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("especes_autorisees", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "quota_annuel_kg",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "taille_minimale_maille",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "profondeur_max_metres", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("bateau_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "nombre_embarcations_max", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "nombre_pecheurs_max", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "montant_paye",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "mode_paiement", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "reference_paiement",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("statut", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("raison_suspension", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("date_suspension", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "est_renouvellement", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "licence_precedente_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "autorite_emission",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "agent_emission", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "bureau_emission",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "document_scan", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("remarques", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("actif", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["bateau_id"], ["bateaux.id"], name="licences_peche_bateau_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["licence_precedente_id"],
            ["licences_peche.id"],
            name="licences_peche_licence_precedente_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["pecheur_id"], ["pecheurs.id"], name="licences_peche_pecheur_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="licences_peche_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_licences_peche_numero_licence",
        "licences_peche",
        ["numero_licence"],
        unique=True,
    )
    op.create_index("ix_licences_peche_id", "licences_peche", ["id"], unique=False)
    op.create_table(
        "armement_cooperatives",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "denomination", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("sigle", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("siege", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column(
            "type_association",
            postgresql.ENUM("ARMEMENT", "COOPERATIVE", name="typeassociation"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "adresse", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "telephone", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "site_web", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "province", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "departement", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "localite", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="armement_cooperatives_pkey"),
    )
    op.create_index(
        "ix_armement_cooperatives_id", "armement_cooperatives", ["id"], unique=False
    )
    op.create_index(
        "ix_armement_cooperatives_code", "armement_cooperatives", ["code"], unique=True
    )
    op.create_table(
        "renouvellements_licences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "licence_actuelle_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("date_demande", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("date_traitement", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("statut", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("motif_rejet", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "nouvelle_licence_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "agent_traitement",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("remarques", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["licence_actuelle_id"],
            ["licences_peche.id"],
            name="renouvellements_licences_licence_actuelle_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["nouvelle_licence_id"],
            ["licences_peche.id"],
            name="renouvellements_licences_nouvelle_licence_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="renouvellements_licences_pkey"),
    )
    op.create_index(
        "ix_renouvellements_licences_id",
        "renouvellements_licences",
        ["id"],
        unique=False,
    )
    op.create_table(
        "inspections_licences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("licence_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date_inspection", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "lieu_inspection",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "type_inspection", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "inspecteur", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "organisme", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("conforme", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("remarques", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("mesures_correctives", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "rapport_scan", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["licence_id"],
            ["licences_peche.id"],
            name="inspections_licences_licence_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="inspections_licences_pkey"),
    )
    op.create_index(
        "ix_inspections_licences_id", "inspections_licences", ["id"], unique=False
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    op.create_table(
        "violations_licences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("licence_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date_violation", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "type_violation", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("lieu", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "type_sanction", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "montant_amende",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "duree_suspension_jours", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("statut", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("date_reglement", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("agent", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["licence_id"],
            ["licences_peche.id"],
            name="violations_licences_licence_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="violations_licences_pkey"),
    )
    op.create_index(
        "ix_violations_licences_id", "violations_licences", ["id"], unique=False
    )
    # ### end Alembic commands ###
