"""Init

Revision ID: ae34d0f3a73d
Revises:
Create Date: 2026-05-21 20:44:54.697975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae34d0f3a73d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_logs_id", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index("ix_bateaux_id", table_name="bateaux")
    op.drop_index("ix_bateaux_numero_immatriculation", table_name="bateaux")
    op.drop_table("bateaux")
    op.drop_index("ix_roles_code", table_name="roles")
    op.drop_index("ix_roles_id", table_name="roles")
    op.drop_table("roles")
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('topology')
    op.drop_index("ix_armement_cooperatives_code", table_name="armement_cooperatives")
    op.drop_index("ix_armement_cooperatives_id", table_name="armement_cooperatives")
    op.drop_table("armement_cooperatives")
    op.drop_index("ix_details_debarquements_id", table_name="details_debarquements")
    op.drop_table("details_debarquements")
    op.drop_index("ix_permissions_code", table_name="permissions")
    op.drop_index("ix_permissions_id", table_name="permissions")
    op.drop_index("ix_permissions_module", table_name="permissions")
    op.drop_table("permissions")
    op.drop_index("ix_especes_code_espece", table_name="especes")
    op.drop_index("ix_especes_id", table_name="especes")
    op.drop_table("especes")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
    op.drop_table("layer")
    op.drop_table("role_permissions")
    op.drop_index("ix_equipages_id", table_name="equipages")
    op.drop_table("equipages")
    op.drop_index(
        "idx_debarcaderes_geom", table_name="debarcaderes", postgresql_using="gist"
    )
    op.drop_index("ix_debarcaderes_code", table_name="debarcaderes")
    op.drop_index("ix_debarcaderes_id", table_name="debarcaderes")
    op.drop_table("debarcaderes")
    op.drop_index("ix_pecheurs_id", table_name="pecheurs")
    op.drop_index("ix_pecheurs_numero_carte", table_name="pecheurs")
    op.drop_table("pecheurs")
    op.drop_table("user_permissions")
    op.drop_index(
        "idx_debarquements_zone_peche_geom",
        table_name="debarquements",
        postgresql_using="gist",
    )
    op.drop_index("ix_debarquements_id", table_name="debarquements")
    op.drop_index("ix_debarquements_numero_debarquement", table_name="debarquements")
    op.drop_table("debarquements")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debarquements",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('debarquements_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "numero_debarquement",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("debarcadere_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("bateau_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "pecheur_principal_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "date_debarquement",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "heure_depart_peche",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "heure_arrivee_debarcadere",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "duree_sortie_heures",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "zone_peche_nom", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "zone_peche_geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "zone_peche_latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "zone_peche_longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "zone_peche_profondeur_m",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "meteo_conditions",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "meteo_etat_mer", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "meteo_temperature_c",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("nombre_pecheurs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("liste_pecheurs_ids", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "photo_captures", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "photo_captures_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "agent_controle_nom",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "agent_controle_matricule",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "signature_pecheur", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "signature_agent", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alerte_espece_protegee", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alerte_quota_depasse", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alerte_taille_illegale", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alerte_bateau_non_conforme",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("alerte_details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("observations", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("anomalies_detectees", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("synchronise", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "date_synchronisation",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["bateau_id"], ["bateaux.id"], name="debarquements_bateau_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["debarcadere_id"],
            ["debarcaderes.id"],
            name="debarquements_debarcadere_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["pecheur_principal_id"],
            ["pecheurs.id"],
            name="debarquements_pecheur_principal_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="debarquements_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_debarquements_numero_debarquement",
        "debarquements",
        ["numero_debarquement"],
        unique=True,
    )
    op.create_index("ix_debarquements_id", "debarquements", ["id"], unique=False)
    op.create_index(
        "idx_debarquements_zone_peche_geom",
        "debarquements",
        ["zone_peche_geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "granted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("granted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name="user_permissions_granted_by_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name="user_permissions_permission_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_permissions_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "permission_id", name="user_permissions_pkey"
        ),
    )
    op.create_table(
        "pecheurs",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('pecheurs_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "numero_carte", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("nom", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("prenom", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("date_naissance", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "lieu_naissance", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "nationalite", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "type_carte", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "numero_piece_identite",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "qr_code_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "empreinte_digitale", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "telephone", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "adresse", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "categorie",
            postgresql.ENUM(
                "ARTISANAL",
                "SEMI_INDUSTRIEL",
                "PATRON",
                "AIDE_PECHEUR",
                name="categoriepecheur",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "debarcadere_habituel_code",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "debarcadere_habituel_nom",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "contact_urgence_nom",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "contact_urgence_telephone",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "contact_urgence_relation",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "statut",
            postgresql.ENUM(
                "ACTIF", "INACTIF", "SUSPENDU", "DECEDE", name="statutpecheur"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pecheurs_pkey"),
        sa.UniqueConstraint(
            "numero_piece_identite", name="pecheurs_numero_piece_identite_key"
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_pecheurs_numero_carte", "pecheurs", ["numero_carte"], unique=True
    )
    op.create_index("ix_pecheurs_id", "pecheurs", ["id"], unique=False)
    op.create_table(
        "debarcaderes",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('debarcaderes_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "denomination", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column(
            "nom_local", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "type",
            postgresql.ENUM(
                "OFFICIEL", "INFORMEL", "SAISONNIER", name="debarcaderetype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "milieu",
            postgresql.ENUM("MARITIME", "FLUVIAL", "LAGUNAIRE", name="milieu"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "province", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "departement", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "localite", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "infrastructure_quai", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "infrastructure_chambre_froide",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "infrastructure_glace", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "infrastructure_marche", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "infrastructure_carburant", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "infrastructure_eau", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "infrastructure_electricite",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("capacite_accueil", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "agent_responsable_nom",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "agent_responsable_matricule",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "agent_responsable_telephone",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "statut_operationnel",
            postgresql.ENUM(
                "ACTIF", "INACTIF", "EN_TRAVAUX", name="statutoperationnel"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("est_localise", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="debarcaderes_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_debarcaderes_id", "debarcaderes", ["id"], unique=False)
    op.create_index("ix_debarcaderes_code", "debarcaderes", ["code"], unique=True)
    op.create_index(
        "idx_debarcaderes_geom",
        "debarcaderes",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_table(
        "equipages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("bateau_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("pecheur_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["bateau_id"], ["bateaux.id"], name="equipages_bateau_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["pecheur_id"], ["pecheurs.id"], name="equipages_pecheur_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="equipages_pkey"),
    )
    op.create_index("ix_equipages_id", "equipages", ["id"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name="role_permissions_permission_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name="role_permissions_role_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "role_id", "permission_id", name="role_permissions_pkey"
        ),
    )
    op.create_table(
        "layer",
        sa.Column("topology_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("layer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("schema_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("table_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feature_column", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("feature_type", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "level",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("child_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["topology_id"], ["topology.id"], name="layer_topology_id_fkey"
        ),
        sa.PrimaryKeyConstraint("topology_id", "layer_id", name="layer_pkey"),
        sa.UniqueConstraint(
            "schema_name",
            "table_name",
            "feature_column",
            name="layer_schema_name_table_name_feature_column_key",
        ),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("nom", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "prenom", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "telephone", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("adresse", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ville", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "code_postal", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column("pays", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "photo_profil", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("signature", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "preferences",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "role",
            postgresql.ENUM(
                "ADMIN", "AGENT", "GESTIONNAIRE", "CONSULTANT", name="userrole"
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_superuser", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "debarcadere_affecte",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "province_affectee",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name="users_role_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "especes",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('especes_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "code_espece", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "nom_scientifique",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "nom_commun_francais",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "nom_commun_fang",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "nom_commun_myene",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("autres_noms_locaux", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "categorie",
            postgresql.ENUM(
                "PELAGIQUE",
                "DEMERSAL",
                "EAU_DOUCE",
                "CRUSTACE",
                "MOLLUSQUE",
                "PROTEGE",
                name="categorieespece",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "famille", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("ordre", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("classe", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("photo", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column(
            "photo_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "statut_reglementaire",
            postgresql.ENUM(
                "LIBRE",
                "SOUS_QUOTA",
                "PROTEGE",
                "SAISONNIER",
                name="statutreglementaire",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "taille_minimale_legale_cm",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "quota_annuel_tonnes",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "quota_mensuel_tonnes",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "quota_hebdomadaire_tonnes",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "saison_peche_debut",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "saison_peche_fin",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "saison_reproduction_debut",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "saison_reproduction_fin",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prix_reference_kg_min",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prix_reference_kg_max",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("habitat", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("alimentation", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "taille_maximale_cm",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "poids_maximal_kg",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "esperance_vie_annees", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "importance_ecologique", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "vulnerabilite_surpeche",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("actif", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="especes_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_especes_id", "especes", ["id"], unique=False)
    op.create_index("ix_especes_code_espece", "especes", ["code_espece"], unique=True)
    op.create_table(
        "permissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("nom", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("module", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("actif", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "date_creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="permissions_pkey"),
    )
    op.create_index("ix_permissions_module", "permissions", ["module"], unique=False)
    op.create_index("ix_permissions_id", "permissions", ["id"], unique=False)
    op.create_index("ix_permissions_code", "permissions", ["code"], unique=True)
    op.create_table(
        "details_debarquements",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("debarquement_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("espece_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "quantite_kg",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("nombre_individus", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "taille_moyenne_cm",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "taille_min_cm",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "taille_max_cm",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prix_unitaire_kg",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "valeur_totale",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "etat_fraicheur", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "destination", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "alerte_taille_illegale", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("alerte_quota", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["debarquement_id"],
            ["debarquements.id"],
            name="details_debarquements_debarquement_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["espece_id"], ["especes.id"], name="details_debarquements_espece_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="details_debarquements_pkey"),
    )
    op.create_index(
        "ix_details_debarquements_id", "details_debarquements", ["id"], unique=False
    )
    op.create_table(
        "armement_cooperatives",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "denomination", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("sigle", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("siege", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.Column(
            "type_association",
            postgresql.ENUM("ARMEMENT", "COOPERATIVE", name="typeassociation"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "adresse", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "telephone", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "site_web", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "date_creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "province", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "departement", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "localite", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="armement_cooperatives_pkey"),
    )
    op.create_index(
        "ix_armement_cooperatives_id", "armement_cooperatives", ["id"], unique=False
    )
    op.create_index(
        "ix_armement_cooperatives_code", "armement_cooperatives", ["code"], unique=True
    )
    op.create_table(
        "topology",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hasz",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="topology_pkey"),
        sa.UniqueConstraint("name", name="topology_name_key"),
    )
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "srid > 0 AND srid <= 998999", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    op.create_table(
        "roles",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('roles_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("nom", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("niveau", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("actif", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("est_systeme", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "date_creation", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="roles_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_roles_id", "roles", ["id"], unique=False)
    op.create_index("ix_roles_code", "roles", ["code"], unique=True)
    op.create_table(
        "bateaux",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "numero_immatriculation",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "nom_bateau", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "type_bateau",
            postgresql.ENUM(
                "PIROGUE",
                "BALEINIERE",
                "CANOT_MOTORISE",
                "FILEYEUR",
                "CHALUTIER_ARTISANAL",
                name="typebateau",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "propulsion",
            postgresql.ENUM(
                "RAME", "VOILE", "MOTEUR_HORS_BORD", "MOTEUR_INBOARD", name="propulsion"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longueur_hors_tout",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "largeur",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tirant_eau",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "jauge_brute",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "moteur_marque", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "moteur_puissance_cv", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "moteur_type_carburant",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "moteur_numero_serie",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "materiau_coque",
            postgresql.ENUM(
                "BOIS", "ALUMINIUM", "FIBRE_VERRE", "ACIER", name="materiaucoque"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "annee_construction", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "chantier_construction",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "engins_peche", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proprietaire_pecheur_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proprietaire_nom",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("nombre_equipage", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "zone_peche_habituelle",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "zone_peche_coordonnees", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "certificat_navigabilite_numero",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "certificat_navigabilite_date_delivrance",
            sa.DATE(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "certificat_navigabilite_date_expiration",
            sa.DATE(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "equipement_gilets_sauvetage",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "equipement_extincteur", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "equipement_radio_vhf", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("equipement_gps", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "equipement_balise_detresse",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "balise_gps_imei", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("balise_gps_actif", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "photo_url", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column("statut", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="bateaux_pkey"),
    )
    op.create_index(
        "ix_bateaux_numero_immatriculation",
        "bateaux",
        ["numero_immatriculation"],
        unique=True,
    )
    op.create_index("ix_bateaux_id", "bateaux", ["id"], unique=False)
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("action", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "user_agent", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="activity_logs_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="activity_logs_pkey"),
    )
    op.create_index("ix_activity_logs_id", "activity_logs", ["id"], unique=False)
    # ### end Alembic commands ###
